In [2]:
import pandas as pd
pd.options.display.max_rows = 150

## Exploring the data

### USDA data set
[Unemployment and median household income for the United States, States, and counties, 2000–23](https://www.ers.usda.gov/data-products/county-level-data-sets/county-level-data-sets-download-data)

In [3]:
df_USDA = pd.read_csv('Data/CountyIncomeUSDA/Unemployment2023.csv')

In [4]:
df_USDA.info()

<class 'pandas.DataFrame'>
RangeIndex: 329726 entries, 0 to 329725
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   FIPS_Code  329726 non-null  int64
 1   State      329726 non-null  str
 2   Area_Name  329726 non-null  str
 3   Attribute  329726 non-null  str
 4   Value      329726 non-null  float64
dtypes: float64(1), int64(1), str(3)
memory usage: 12.6 MB

Federal Information Processing System (FIPS) codes identify geographic areas by state and county.
[FIPS Code details](https://transition.fcc.gov/oet/info/maps/census/fips/fips.txt)

In [5]:
df_USDA.head(10)

   FIPS_Code State      Area_Name                  Attribute        Value
0          0    US  United States  Civilian_labor_force_2000  142601576.0
1          0    US  United States              Employed_2000  136904853.0
2          0    US  United States            Unemployed_2000    5696723.0
3          0    US  United States     Unemployment_rate_2000          4.0
4          0    US  United States  Civilian_labor_force_2001  143786537.0
5          0    US  United States              Employed_2001  136977996.0
6          0    US  United States            Unemployed_2001    6808541.0
7          0    US  United States     Unemployment_rate_2001          4.7
8          0    US  United States  Civilian_labor_force_2002  144839298.0
9          0    US  United States              Employed_2002  136455783.0

In [6]:
# Pull attributes so I can explore 
df_attributes = df_USDA['Attribute']
df_attributes.value_counts()

Attribute
Civilian_labor_force_2021                    3273
Employed_2021                                3273
Unemployed_2021                              3273
Unemployment_rate_2021                       3273
Civilian_labor_force_2022                    3273
Employed_2022                                3273
Unemployed_2022                              3273
Unemployment_rate_2022                       3273
Civilian_labor_force_2023                    3273
Employed_2023                                3273
Unemployed_2023                              3273
Unemployment_rate_2023                       3273
Civilian_labor_force_2010                    3272
Employed_2010                                3272
Unemployed_2010                              3272
Unemployment_rate_2010                       3272
Civilian_labor_force_2011                    3272
Employed_2011                                3272
Unemployed_2011                              3272
Unemployment_rate_2011                       3272
Civilian_labor_force_2012                    3272
Employed_2012                                3272
Unemployed_2012                              3272
Unemployment_rate_2012                       3272
Civilian_labor_force_2013                    3272
Employed_2013                                3272
Unemployed_2013                              3272
Unemployment_rate_2013                       3272
Civilian_labor_force_2014                    3272
Employed_2014                                3272
Unemployed_2014                              3272
Unemployment_rate_2014                       3272
Civilian_labor_force_2015                    3272
Employed_2015                                3272
Unemployed_2015                              3272
Unemployment_rate_2015                       3272
Civilian_labor_force_2016                    3272
Employed_2016                                3272
Unemployed_2016                              3272
Unemployment_rate_2016                       3272
Civilian_labor_force_2017                    3272
Employed_2017                                3272
Unemployed_2017                              3272
Unemployment_rate_2017                       3272
Civilian_labor_force_2018                    3272
Employed_2018                                3272
Unemployed_2018                              3272
Unemployment_rate_2018                       3272
Civilian_labor_force_2019                    3272
Employed_2019                                3272
Unemployed_2019                              3272
Unemployment_rate_2019                       3272
Civilian_labor_force_2000                    3270
Employed_2000                                3270
Unemployed_2000                              3270
Unemployment_rate_2000                       3270
Civilian_labor_force_2001                    3270
Employed_2001                                3270
Unemployed_2001                              3270
Unemployment_rate_2001                       3270
Civilian_labor_force_2002                    3270
Employed_2002                                3270
Unemployed_2002                              3270
Unemployment_rate_2002                       3270
Civilian_labor_force_2003                    3270
Employed_2003                                3270
Unemployed_2003                              3270
Unemployment_rate_2003                       3270
Civilian_labor_force_2004                    3270
Employed_2004                                3270
Unemployed_2004                              3270
Unemployment_rate_2004                       3270
Civilian_labor_force_2007                    3270
Employed_2007                                3270
Unemployed_2007                              3270
Unemployment_rate_2007                       3270
Civilian_labor_force_2008                    3270
Employed_2008                                3270
Unemployed_2008                              3270
Unemployment_rate_2008                       3270
Civilian_labor_force_2009                    3270
Employed_2009                                3270
Unemployed_2009                              3270
Unemployment_rate_2009                       3270
Civilian_labor_force_2005                    3263
Employed_2005                                3263
Unemployed_2005                              3263
Unemployment_rate_2005                       3263
Civilian_labor_force_2006                    3263
Employed_2006                                3263
Unemployed_2006                              3263
Unemployment_rate_2006                       3263
Rural_Urban_Continuum_Code_2023              3221
Metro_2023                                   3221
Urban_Influence_Code_2013                    3219
Median_Household_Income_2022                 3195
Civilian_labor_force_2020                    3194
Employed_2020                                3194
Unemployed_2020                              3194
Unemployment_rate_2020                       3194
Med_HH_Income_Percent_of_State_Total_2022    3194
Name: count, dtype: int64

In [7]:
# Remove year so I can see genneral types of info available
df_attributes = df_attributes.replace(r'_[0-9]+', '', regex=True).str.strip()
df_attributes.value_counts()

Attribute
Civilian_labor_force                    78419
Employed                                78419
Unemployed                              78419
Unemployment_rate                       78419
Rural_Urban_Continuum_Code               3221
Metro                                    3221
Urban_Influence_Code                     3219
Median_Household_Income                  3195
Med_HH_Income_Percent_of_State_Total     3194
Name: count, dtype: int64

### CDC data set
[Local Data for Better Health, County Data, 2025 release](https://data.cdc.gov/500-Cities-Places/PLACES-Local-Data-for-Better-Health-County-Data-20/swc5-untb/about_data)

In [11]:
dtype_dict = {'Data_Value_Footnote_Symbol': 'str', 'Data_Value_Footnote': 'str'}
df_CDC = pd.read_csv('Data/CountyCDC/PLACES__Local_Data_for_Better_Health,_County_Data,_2025_release_20260325.csv', dtype=dtype_dict)

In [12]:
df_CDC.info()

<class 'pandas.DataFrame'>
RangeIndex: 229298 entries, 0 to 229297
Data columns (total 22 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Year                        229298 non-null  int64
 1   StateAbbr                   229298 non-null  str
 2   StateDesc                   229298 non-null  str
 3   LocationName                229218 non-null  str
 4   DataSource                  229298 non-null  str
 5   Category                    229298 non-null  str
 6   Measure                     229298 non-null  str
 7   Data_Value_Unit             229298 non-null  str
 8   Data_Value_Type             229298 non-null  str
 9   Data_Value                  229232 non-null  float64
 10  Data_Value_Footnote_Symbol  80 non-null      str
 11  Data_Value_Footnote         80 non-null      str
 12  Low_Confidence_Limit        229232 non-null  float64
 13  High_Confidence_Limit       229232 non-null  float64
 14  TotalPopulation             229298 non-null  str
 15  TotalPop18plus              229298 non-null  str
 16  LocationID                  229298 non-null  int64
 17  CategoryID                  229298 non-null  str
 18  MeasureId                   229298 non-null  str
 19  DataValueTypeID             229298 non-null  str
 20  Short_Question_Text         229298 non-null  str
 21  Geolocation                 229218 non-null  str
dtypes: float64(3), int64(2), str(17)
memory usage: 38.5 MB

In [13]:
df_CDC.head(10)

,Year,StateAbbr,StateDesc,LocationName,DataSource,Category,Measure,Data_Value_Unit,Data_Value_Type,Data_Value,...,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,TotalPop18plus,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text,Geolocation
0,2023,AR,Arkansas,Drew,BRFSS,Health Outcomes,Arthritis among adults,%,Crude prevalence,29.9,...,26.6,33.3,"16,945","13,230",5043,HLTHOUT,ARTHRITIS,CrdPrv,Arthritis,POINT (-91.7196579038053 33.5894113647675)
1,2023,AR,Arkansas,Fulton,BRFSS,Health Outcomes,Current asthma among adults,%,Crude prevalence,10.6,...,9.2,11.9,"12,421","9,795",5049,HLTHOUT,CASTHMA,CrdPrv,Current Asthma,POINT (-91.817888079321 36.3816206347765)
2,2023,AR,Arkansas,Howard,BRFSS,Health Outcomes,Arthritis among adults,%,Crude prevalence,31.2,...,27.7,34.8,"12,533","9,311",5061,HLTHOUT,ARTHRITIS,CrdPrv,Arthritis,POINT (-93.9938053308515 34.0889044688856)
3,2023,AR,Arkansas,Miller,BRFSS,Health Outcomes,Stroke among adults,%,Crude prevalence,4.7,...,4.2,5.3,"42,415","32,396",5091,HLTHOUT,STROKE,CrdPrv,Stroke,POINT (-93.8924281761086 33.3123156126392)
4,2023,AR,Arkansas,Ouachita,BRFSS,Disability,Any disability among adults,%,Crude prevalence,42.8,...,37.9,47.8,"21,793","16,948",5103,DISABLT,DISABILITY,CrdPrv,Any Disability,POINT (-92.882040791321 33.593253927504)
5,2023,AR,Arkansas,Pulaski,BRFSS,Health Outcomes,Stroke among adults,%,Crude prevalence,3.9,...,3.4,4.3,"400,009","307,397",5119,HLTHOUT,STROKE,CrdPrv,Stroke,POINT (-92.3119548341849 34.7700394452014)
6,2023,AR,Arkansas,Van Buren,BRFSS,Health Outcomes,Stroke among adults,%,Crude prevalence,5.4,...,4.7,6.2,"16,142","13,054",5141,HLTHOUT,STROKE,CrdPrv,Stroke,POINT (-92.5158922653774 35.5806118772188)
7,2023,CA,California,Marin,BRFSS,Disability,Any disability among adults,%,Crude prevalence,27.5,...,23.2,32.0,"254,407","206,190",6041,DISABLT,DISABILITY,CrdPrv,Any Disability,POINT (-122.72355494043 38.0735138436081)
8,2023,CO,Colorado,Dolores,BRFSS,Health Outcomes,Arthritis among adults,%,Crude prevalence,30.2,...,26.7,33.9,"2,513","2,096",8033,HLTHOUT,ARTHRITIS,CrdPrv,Arthritis,POINT (-108.517382189661 37.7520546286538)
9,2023,CO,Colorado,Lake,BRFSS,Health Outcomes,Current asthma among adults,%,Crude prevalence,10.2,...,9.0,11.6,"7,365","5,869",8065,HLTHOUT,CASTHMA,CrdPrv,Current Asthma,POINT (-106.344971513974 39.2024367117474)

### MIT data set
[County Presidential Election Returns 2000-2024](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/VOQCHQ)

In [14]:
df_MIT = pd.read_csv('Data/CountyPresidentalMIT/countypres_2000-2024.csv')

In [15]:
df_MIT.info()

<class 'pandas.DataFrame'>
RangeIndex: 94151 entries, 0 to 94150
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   state           94151 non-null  str
 1   county_name     94151 non-null  str
 2   year            94151 non-null  int64
 3   state_po        94151 non-null  str
 4   county_fips     94099 non-null  float64
 5   office          94151 non-null  str
 6   candidate       94151 non-null  str
 7   party           93650 non-null  str
 8   candidatevotes  94114 non-null  float64
 9   totalvotes      94151 non-null  int64
 10  version         94151 non-null  int64
 11  mode            91356 non-null  str
dtypes: float64(2), int64(3), str(7)
memory usage: 8.6 MB

In [16]:
df_MIT.head(10)

,state,county_name,year,state_po,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode
0,ALABAMA,AUTAUGA,2024,AL,1001.0,US PRESIDENT,OTHER,OTHER,293.0,28281,20260225,TOTAL
1,ALABAMA,AUTAUGA,2024,AL,1001.0,US PRESIDENT,CHASE OLIVER,LIBERTARIAN,65.0,28281,20260225,TOTAL
2,ALABAMA,AUTAUGA,2024,AL,1001.0,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,7439.0,28281,20260225,TOTAL
3,ALABAMA,AUTAUGA,2024,AL,1001.0,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,20484.0,28281,20260225,TOTAL
4,ALABAMA,BALDWIN,2024,AL,1003.0,US PRESIDENT,OTHER,OTHER,1276.0,122249,20260225,TOTAL
5,ALABAMA,BALDWIN,2024,AL,1003.0,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,95798.0,122249,20260225,TOTAL
6,ALABAMA,BALDWIN,2024,AL,1003.0,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,24934.0,122249,20260225,TOTAL
7,ALABAMA,BALDWIN,2024,AL,1003.0,US PRESIDENT,CHASE OLIVER,LIBERTARIAN,241.0,122249,20260225,TOTAL
8,ALABAMA,BARBOUR,2024,AL,1005.0,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,5606.0,9855,20260225,TOTAL
9,ALABAMA,BARBOUR,2024,AL,1005.0,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,4158.0,9855,20260225,TOTAL

### Questions and notes

Data will be joined using the FIPS code (CDC has it as location code, just verify it IS FIPS)

I want to know...
1) Do red/blue counties differ in addiction, life expectency or uninsured rate?
2) Which states show the biggest gaps in outcomes based off voting?
3) What's the stronger predictor of those outcomes, voting or income?